project_id = "reservas-aulas-edeca"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://127.0.0.1:8781"
additional_redirect_urls = ["https://escuela-de-ciencias-ambientales.github.io/reservas_aulas/"]
jwt_expiry = 3600
enable_signup = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-manage-users]
verify_jwt = true
