create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  plate text not null unique,
  make text not null,
  model text not null,
  model_year integer not null check (model_year between 1990 and 2100),
  display_name text not null,
  image_path text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.vehicles (plate, make, model, model_year, display_name, image_path, sort_order)
values
  ('301-419', 'Mitsubishi', 'L200', 2012, 'Mitsubishi L200 2012', 'vehiculo-mitsubishi-l200.jpg', 1),
  ('301-599', 'Toyota', 'Hilux', 2025, 'Toyota Hilux 2025', 'vehiculo-toyota-hilux.jpg', 2)
on conflict (plate) do update set
  make = excluded.make,
  model = excluded.model,
  model_year = excluded.model_year,
  display_name = excluded.display_name,
  image_path = excluded.image_path,
  active = true,
  sort_order = excluded.sort_order;

create table if not exists public.vehicle_maintenance (
  id uuid primary key default gen_random_uuid(),
  vehicle_id bigint not null references public.vehicles(id) on delete restrict,
  starts_at timestamptz not null,
  ends_at timestamptz,
  category text not null check (category in ('oil_change', 'minor_repair', 'major_repair')),
  details text check (details is null or char_length(trim(details)) <= 240),
  active boolean not null default true,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or starts_at < ends_at)
);

create table if not exists public.vehicle_reservations (
  id uuid primary key default gen_random_uuid(),
  vehicle_id bigint not null references public.vehicles(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete restrict,
  responsible_name text not null check (char_length(trim(responsible_name)) between 3 and 100),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  destination text not null check (char_length(trim(destination)) between 2 and 160),
  objective text not null check (char_length(trim(objective)) between 3 and 240),
  additional_drivers text[] not null default '{}',
  status text not null default 'confirmed'
    check (status in ('confirmed', 'suspended_maintenance', 'cancelled')),
  maintenance_id uuid references public.vehicle_maintenance(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cancelled_at timestamptz,
  check (starts_at < ends_at),
  check (cardinality(additional_drivers) <= 2),
  exclude using gist (
    vehicle_id with =,
    tstzrange(starts_at, ends_at, '[)') with &&
  ) where (status in ('confirmed', 'suspended_maintenance'))
);

create table if not exists public.vehicle_service_schedules (
  vehicle_id bigint primary key references public.vehicles(id) on delete cascade,
  current_mileage integer check (current_mileage is null or current_mileage >= 0),
  next_oil_date date,
  next_oil_mileage integer check (next_oil_mileage is null or next_oil_mileage >= 0),
  next_dekra_month date,
  notes text check (notes is null or char_length(trim(notes)) <= 240),
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.vehicle_service_schedules (vehicle_id, next_dekra_month)
select id, date '2026-09-01' from public.vehicles
on conflict (vehicle_id) do nothing;

create index if not exists vehicle_reservations_period_idx
  on public.vehicle_reservations(vehicle_id, starts_at, ends_at);
create index if not exists vehicle_reservations_user_idx
  on public.vehicle_reservations(user_id, starts_at);
create index if not exists vehicle_maintenance_period_idx
  on public.vehicle_maintenance(vehicle_id, starts_at, ends_at);

drop trigger if exists vehicles_set_updated_at on public.vehicles;
create trigger vehicles_set_updated_at before update on public.vehicles
for each row execute function public.set_updated_at();
drop trigger if exists vehicle_maintenance_set_updated_at on public.vehicle_maintenance;
create trigger vehicle_maintenance_set_updated_at before update on public.vehicle_maintenance
for each row execute function public.set_updated_at();
drop trigger if exists vehicle_reservations_set_updated_at on public.vehicle_reservations;
create trigger vehicle_reservations_set_updated_at before update on public.vehicle_reservations
for each row execute function public.set_updated_at();

create or replace function public.protect_vehicle_reservation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  profile_name text;
  active_cycle public.reservation_cycles;
begin
  if tg_op = 'INSERT' then
    select * into active_cycle from public.reservation_cycles where is_current = true;
    if not found or not active_cycle.reservations_enabled
      or now() < active_cycle.booking_opens_at or now() > active_cycle.booking_closes_at then
      raise exception using errcode = '22023', message = 'Las reservas están cerradas por la administración';
    end if;
    if new.starts_at::date < active_cycle.reservation_start_date
      or new.ends_at::date > active_cycle.reservation_end_date then
      raise exception using errcode = '22023', message = 'La fecha está fuera del periodo de reservación';
    end if;
    if new.starts_at < now() then
      raise exception using errcode = '22023', message = 'No se permiten reservas en fechas pasadas';
    end if;
    if not public.is_admin() and new.user_id <> auth.uid() then
      raise exception using errcode = '42501', message = 'No puedes reservar a nombre de otra persona';
    end if;
    select full_name into profile_name
    from public.profiles where id = new.user_id and active = true;
    if profile_name is null then
      raise exception using errcode = '22023', message = 'El responsable no tiene un perfil activo';
    end if;
    new.responsible_name := profile_name;
    new.status := 'confirmed';
    new.maintenance_id := null;
    if exists (
      select 1 from public.vehicle_maintenance m
      where m.vehicle_id = new.vehicle_id and m.active
        and tstzrange(m.starts_at, coalesce(m.ends_at, 'infinity'::timestamptz), '[)')
          && tstzrange(new.starts_at, new.ends_at, '[)')
    ) then
      raise exception using errcode = '23P01', message = 'El vehículo está en mantenimiento durante ese periodo';
    end if;
  elsif not public.is_admin() then
    if old.user_id <> auth.uid() or new.status <> 'cancelled'
      or new.vehicle_id <> old.vehicle_id or new.starts_at <> old.starts_at
      or new.ends_at <> old.ends_at or new.destination <> old.destination
      or new.objective <> old.objective or new.additional_drivers <> old.additional_drivers then
      raise exception using errcode = '42501', message = 'Solo puedes cancelar tus propias reservas';
    end if;
  end if;
  if tg_op = 'UPDATE' then
    select full_name into profile_name
    from public.profiles where id = new.user_id and active = true;
    if profile_name is null then
      raise exception using errcode = '22023', message = 'El responsable no tiene un perfil activo';
    end if;
    new.responsible_name := profile_name;
  end if;
  if tg_op = 'UPDATE' and new.status = 'cancelled' and old.status is distinct from 'cancelled' then
    new.cancelled_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists vehicle_reservations_protect on public.vehicle_reservations;
create trigger vehicle_reservations_protect
before insert or update on public.vehicle_reservations
for each row execute function public.protect_vehicle_reservation();

alter table public.vehicles enable row level security;
alter table public.vehicle_maintenance enable row level security;
alter table public.vehicle_reservations enable row level security;
alter table public.vehicle_service_schedules enable row level security;

drop policy if exists "Vehiculos visibles" on public.vehicles;
create policy "Vehiculos visibles" on public.vehicles for select using (active = true);
drop policy if exists "Usuarios consultan reservas vehiculares" on public.vehicle_reservations;
create policy "Usuarios consultan reservas vehiculares"
on public.vehicle_reservations for select to authenticated using (true);
drop policy if exists "Docentes crean reserva vehicular" on public.vehicle_reservations;
create policy "Docentes crean reserva vehicular"
on public.vehicle_reservations for insert to authenticated
with check (user_id = auth.uid() or public.is_admin());
drop policy if exists "Usuarios cancelan reserva vehicular" on public.vehicle_reservations;
create policy "Usuarios cancelan reserva vehicular"
on public.vehicle_reservations for update to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());
drop policy if exists "Usuarios consultan mantenimiento" on public.vehicle_maintenance;
create policy "Usuarios consultan mantenimiento"
on public.vehicle_maintenance for select to authenticated using (true);
drop policy if exists "Administracion gestiona mantenimiento" on public.vehicle_maintenance;
create policy "Administracion gestiona mantenimiento"
on public.vehicle_maintenance for all to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Administracion consulta obligaciones vehiculares" on public.vehicle_service_schedules;
create policy "Administracion consulta obligaciones vehiculares"
on public.vehicle_service_schedules for select to authenticated using (public.is_admin());
drop policy if exists "Administracion gestiona obligaciones vehiculares" on public.vehicle_service_schedules;
create policy "Administracion gestiona obligaciones vehiculares"
on public.vehicle_service_schedules for all to authenticated
using (public.is_admin()) with check (public.is_admin());

create or replace function public.get_public_vehicle_overview()
returns table (
  id bigint, plate text, display_name text, make text, model text, model_year integer,
  image_path text, maintenance_category text, maintenance_starts_at timestamptz,
  maintenance_ends_at timestamptz, current_mileage integer,
  next_oil_date date, next_oil_mileage integer
)
language sql
stable
security definer
set search_path = public
as $$
  select v.id, v.plate, v.display_name, v.make, v.model, v.model_year, v.image_path,
    m.category, m.starts_at, m.ends_at,
    s.current_mileage, s.next_oil_date, s.next_oil_mileage
  from public.vehicles v
  left join lateral (
    select category, starts_at, ends_at from public.vehicle_maintenance
    where vehicle_id = v.id and active
      and tstzrange(starts_at, coalesce(ends_at, 'infinity'::timestamptz), '[)') @> now()
    order by starts_at desc limit 1
  ) m on true
  left join public.vehicle_service_schedules s on s.vehicle_id = v.id
  where v.active
  order by v.sort_order, v.plate;
$$;

create or replace function public.get_public_vehicle_calendar(p_from date, p_to date)
returns table (
  id uuid, vehicle_id bigint, starts_at timestamptz, ends_at timestamptz,
  responsible_name text, status text, event_type text, category text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if p_to < p_from or p_to - p_from > 370 then
    raise exception using errcode = '22023', message = 'El rango solicitado no es válido';
  end if;
  return query
  select r.id, r.vehicle_id, r.starts_at, r.ends_at, r.responsible_name,
    r.status, 'reservation'::text, null::text
  from public.vehicle_reservations r
  where r.status <> 'cancelled'
    and r.starts_at < (p_to + 1)::timestamptz and r.ends_at > p_from::timestamptz
  union all
  select m.id, m.vehicle_id, m.starts_at, coalesce(m.ends_at, (p_to + 1)::timestamptz),
    null::text, 'maintenance'::text, 'maintenance'::text, m.category
  from public.vehicle_maintenance m
  where m.active and m.starts_at < (p_to + 1)::timestamptz
    and coalesce(m.ends_at, 'infinity'::timestamptz) > p_from::timestamptz;
end;
$$;

create or replace function public.admin_set_vehicle_maintenance(
  p_vehicle_id bigint, p_starts_at timestamptz, p_ends_at timestamptz,
  p_category text, p_details text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare new_id uuid;
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'Se requiere acceso administrativo';
  end if;
  if p_category not in ('oil_change', 'minor_repair', 'major_repair')
    or (p_ends_at is not null and p_starts_at >= p_ends_at) then
    raise exception using errcode = '22023', message = 'Los datos de mantenimiento no son válidos';
  end if;
  insert into public.vehicle_maintenance
    (vehicle_id, starts_at, ends_at, category, details, created_by)
  values
    (p_vehicle_id, p_starts_at, p_ends_at, p_category, nullif(trim(p_details), ''), auth.uid())
  returning id into new_id;
  update public.vehicle_reservations
  set status = 'suspended_maintenance', maintenance_id = new_id
  where vehicle_id = p_vehicle_id and status = 'confirmed'
    and tstzrange(starts_at, ends_at, '[)')
      && tstzrange(p_starts_at, coalesce(p_ends_at, 'infinity'::timestamptz), '[)');
  return new_id;
end;
$$;

create or replace function public.admin_close_vehicle_maintenance(p_id uuid, p_ends_at timestamptz)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'Se requiere acceso administrativo';
  end if;
  update public.vehicle_maintenance
  set active = false,
      ends_at = greatest(coalesce(p_ends_at, now()), starts_at + interval '1 minute')
  where id = p_id;
end;
$$;

create or replace function public.admin_resolve_vehicle_reservation(
  p_id uuid, p_action text, p_vehicle_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare item public.vehicle_reservations;
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'Se requiere acceso administrativo';
  end if;
  select * into item from public.vehicle_reservations where id = p_id for update;
  if not found then raise exception using errcode = '22023', message = 'Reserva no encontrada'; end if;
  if p_action = 'cancel' then
    update public.vehicle_reservations set status = 'cancelled' where id = p_id;
  elsif p_action in ('reactivate', 'reassign') then
    if exists (
      select 1 from public.vehicle_maintenance m
      where m.vehicle_id = case when p_action = 'reassign' then coalesce(p_vehicle_id, item.vehicle_id) else item.vehicle_id end
        and m.active
        and tstzrange(m.starts_at, coalesce(m.ends_at, 'infinity'::timestamptz), '[)')
          && tstzrange(item.starts_at, item.ends_at, '[)')
    ) then
      raise exception using errcode = '23P01', message = 'El vehículo continúa bloqueado por mantenimiento en ese periodo';
    end if;
    update public.vehicle_reservations
    set vehicle_id = case when p_action = 'reassign' then coalesce(p_vehicle_id, vehicle_id) else vehicle_id end,
        status = 'confirmed', maintenance_id = null
    where id = p_id;
  else
    raise exception using errcode = '22023', message = 'Acción no válida';
  end if;
end;
$$;

create or replace function public.admin_upsert_vehicle_service(
  p_vehicle_id bigint, p_current_mileage integer, p_next_oil_date date,
  p_next_oil_mileage integer, p_next_dekra_month date, p_notes text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'Se requiere acceso administrativo';
  end if;
  insert into public.vehicle_service_schedules
    (vehicle_id, current_mileage, next_oil_date, next_oil_mileage, next_dekra_month, notes, updated_by)
  values
    (p_vehicle_id, p_current_mileage, p_next_oil_date, p_next_oil_mileage,
     case when p_next_dekra_month is null then null else date_trunc('month', p_next_dekra_month)::date end,
     nullif(trim(p_notes), ''), auth.uid())
  on conflict (vehicle_id) do update set
    current_mileage = excluded.current_mileage,
    next_oil_date = excluded.next_oil_date,
    next_oil_mileage = excluded.next_oil_mileage,
    next_dekra_month = excluded.next_dekra_month,
    notes = excluded.notes,
    updated_by = auth.uid(),
    updated_at = now();
end;
$$;

grant execute on function public.get_public_vehicle_overview() to anon, authenticated;
grant execute on function public.get_public_vehicle_calendar(date, date) to anon, authenticated;
grant execute on function public.admin_set_vehicle_maintenance(bigint, timestamptz, timestamptz, text, text) to authenticated;
grant execute on function public.admin_close_vehicle_maintenance(uuid, timestamptz) to authenticated;
grant execute on function public.admin_resolve_vehicle_reservation(uuid, text, bigint) to authenticated;
grant execute on function public.admin_upsert_vehicle_service(bigint, integer, date, integer, date, text) to authenticated;
