create table if not exists public.teacher_registry (
  id bigint generated by default as identity primary key,
  email text not null unique check (email ~ '^[a-z0-9-]+\.[a-z0-9-]+\.[a-z0-9-]+@una\.cr$'),
  full_name text not null check (char_length(trim(full_name)) between 3 and 100),
  active boolean not null default true,
  claimed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists teacher_registry_set_updated_at on public.teacher_registry;
create trigger teacher_registry_set_updated_at
before update on public.teacher_registry
for each row execute function public.set_updated_at();

alter table public.teacher_registry enable row level security;

drop policy if exists "Administración consulta docentes autorizados" on public.teacher_registry;
create policy "Administración consulta docentes autorizados"
on public.teacher_registry for select
to authenticated
using (public.is_admin());

drop policy if exists "Administración gestiona docentes autorizados" on public.teacher_registry;
create policy "Administración gestiona docentes autorizados"
on public.teacher_registry for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant select, insert, update on public.teacher_registry to authenticated;
grant usage, select on sequence public.teacher_registry_id_seq to authenticated;

insert into public.teacher_registry (email, full_name, active, claimed_at)
select email, full_name, active, created_at
from public.profiles
where role = 'teacher'
on conflict (email) do update
set full_name = excluded.full_name,
    active = excluded.active,
    claimed_at = coalesce(public.teacher_registry.claimed_at, excluded.claimed_at);

comment on table public.teacher_registry is 'Lista administrativa de docentes autorizados para crear o utilizar una cuenta';
