create extension if not exists btree_gist with schema extensions;

create type public.user_role as enum ('teacher', 'admin');
create type public.reservation_status as enum ('active', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique check (email ~ '^[a-z0-9-]+\.[a-z0-9-]+\.[a-z0-9-]+@una\.cr$'),
  full_name text not null check (char_length(trim(full_name)) between 3 and 100),
  role public.user_role not null default 'teacher',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.classrooms (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  active boolean not null default true,
  sort_order integer not null default 0
);

create table public.fixed_occupancies (
  id bigint generated by default as identity primary key,
  classroom_id bigint not null references public.classrooms(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time not null,
  end_time time not null,
  label text not null,
  check (start_time < end_time)
);

create table public.reservations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete restrict,
  classroom_id bigint not null references public.classrooms(id) on delete restrict,
  reservation_date date not null,
  start_time time not null,
  end_time time not null,
  activity text not null check (char_length(trim(activity)) between 3 and 120),
  professor_name text not null check (char_length(trim(professor_name)) between 3 and 100),
  status public.reservation_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cancelled_at timestamptz,
  check (start_time < end_time),
  check (start_time >= time '07:00' and end_time <= time '21:30'),
  check (reservation_date between date '2026-07-20' and date '2026-12-20'),
  exclude using gist (
    classroom_id with =,
    tsrange(reservation_date + start_time, reservation_date + end_time, '[)') with &&
  ) where (status = 'active')
);

create index reservations_user_date_idx on public.reservations(user_id, reservation_date);
create index reservations_date_room_idx on public.reservations(reservation_date, classroom_id);
create index fixed_occupancies_room_day_idx on public.fixed_occupancies(classroom_id, day_of_week);

insert into public.classrooms (code, name, sort_order) values
  ('L601', 'Laboratorio L01', 1),
  ('L602', 'Laboratorio L602', 2),
  ('L603', 'Laboratorio L603', 3),
  ('708', 'Aula 708', 4),
  ('709', 'Aula 709', 5),
  ('710', 'Aula 710', 6),
  ('711', 'Aula 711', 7)
on conflict (code) do update set name = excluded.name, sort_order = excluded.sort_order, active = true;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger reservations_set_updated_at
before update on public.reservations
for each row execute function public.set_updated_at();

create or replace function public.enforce_teacher_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role = 'teacher' then
    if tg_op = 'INSERT' and (select count(*) from public.profiles where role = 'teacher') >= 50 then
      raise exception using errcode = '23514', message = 'Se alcanzó el máximo de 50 cuentas docentes';
    elsif tg_op = 'UPDATE' and old.role <> 'teacher' and (select count(*) from public.profiles where role = 'teacher') >= 50 then
      raise exception using errcode = '23514', message = 'Se alcanzó el máximo de 50 cuentas docentes';
    end if;
  end if;
  return new;
end;
$$;

create trigger profiles_enforce_teacher_limit
before insert or update of role on public.profiles
for each row execute function public.enforce_teacher_limit();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    lower(coalesce(new.email, '')),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(coalesce(new.email, 'Docente'), '@', 1)),
    case when new.raw_user_meta_data ->> 'role' = 'admin' then 'admin'::public.user_role else 'teacher'::public.user_role end
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.protect_reservation_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  fixed_label text;
begin
  if new.reservation_date < current_date then
    raise exception using errcode = '22023', message = 'No se permiten reservas en fechas pasadas';
  end if;

  if extract(dow from new.reservation_date)::integer = 0 then
    raise exception using errcode = '22023', message = 'No se permiten reservas los domingos';
  end if;

  select fixed.label into fixed_label
  from public.fixed_occupancies fixed
  where fixed.classroom_id = new.classroom_id
    and new.reservation_date <= date '2026-11-14'
    and fixed.day_of_week = extract(dow from new.reservation_date)::integer
    and new.start_time < fixed.end_time
    and new.end_time > fixed.start_time
  limit 1;

  if fixed_label is not null then
    raise exception using errcode = '23P01', message = 'El horario coincide con una ocupación académica fija';
  end if;

  if tg_op = 'INSERT' then
    new.professor_name = (select full_name from public.profiles where id = new.user_id);
  else
    if not public.is_admin() and (
      new.user_id <> old.user_id
      or new.classroom_id <> old.classroom_id
      or new.reservation_date <> old.reservation_date
      or new.start_time <> old.start_time
      or new.end_time <> old.end_time
      or new.activity <> old.activity
      or new.professor_name <> old.professor_name
    ) then
      raise exception using errcode = '42501', message = 'Solo la administración puede modificar los datos de una reserva';
    end if;
    if old.status = 'active' and new.status = 'cancelled' then
      new.cancelled_at = now();
    end if;
  end if;

  return new;
end;
$$;

create trigger reservations_protect_fields
before insert or update on public.reservations
for each row execute function public.protect_reservation_fields();

alter table public.profiles enable row level security;
alter table public.classrooms enable row level security;
alter table public.fixed_occupancies enable row level security;
alter table public.reservations enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  );
$$;

create policy "Aulas visibles para todos"
on public.classrooms for select
using (active = true);

create policy "Ocupaciones fijas visibles para todos"
on public.fixed_occupancies for select
using (true);

create policy "Perfil propio o administración"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

create policy "Administración actualiza perfiles"
on public.profiles for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Reservas activas visibles para todos"
on public.reservations for select
using (status = 'active' or user_id = auth.uid() or public.is_admin());

create policy "Docentes crean sus reservas"
on public.reservations for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (select 1 from public.profiles where id = auth.uid() and active = true)
);

create policy "Propietarios cancelan sus reservas"
on public.reservations for update
to authenticated
using (user_id = auth.uid() and status = 'active')
with check (user_id = auth.uid() and status = 'cancelled');

create policy "Administración gestiona todas las reservas"
on public.reservations for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant usage on schema public to anon, authenticated;
grant select on public.classrooms, public.fixed_occupancies to anon, authenticated;
grant select on public.reservations to anon, authenticated;
grant select on public.profiles to authenticated;
grant insert, update on public.reservations to authenticated;
grant update on public.profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

comment on table public.reservations is 'Reservas de aulas realizadas por personal docente autorizado';
comment on table public.fixed_occupancies is 'Horario académico recurrente que bloquea reservas durante el ciclo';
